{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "concourse.fullname" . }}-pod-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "concourse.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "concourse.fullname" . }}-pod-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "concourse.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concourse.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "concourse.fullname" . }}-pod-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
