apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "concourse.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "concourse.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "concourse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "concourse.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "concourse.serviceAccountName" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: generate-keys
          image: {{ include "concourse.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - |
              # Only generate keys if they don't already exist
              if [ ! -f /keys/session_signing_key ]; then
                concourse generate-key -t rsa -f /keys/session_signing_key
              fi
              if [ ! -f /keys/tsa_host_key ]; then
                concourse generate-key -t ssh -f /keys/tsa_host_key
              fi
              if [ ! -f /keys/worker_key ]; then
                concourse generate-key -t ssh -f /keys/worker_key
                cp /keys/worker_key.pub /keys/authorized_worker_keys
              fi
          volumeMounts:
            - name: keys
              mountPath: /keys
        - name: migrate-db
          image: {{ include "concourse.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - --migrate-to-latest-version
            - --postgres-host={{ include "concourse.postgresHost" . }}
            - --postgres-port={{ include "concourse.postgresPort" . }}
            {{- if .Values.postgresql.socket }}
            - --postgres-socket={{ .Values.postgresql.socket }}
            {{- end }}
            - --postgres-user={{ .Values.postgresql.user }}
            {{- if not .Values.postgresql.existingSecret }}
            - --postgres-password={{ .Values.postgresql.password }}
            {{- end }}
            - --postgres-database={{ .Values.postgresql.database }}
            {{- if ne .Values.postgresql.sslmode "disable" }}
            - --postgres-sslmode={{ .Values.postgresql.sslmode }}
            {{- end }}
            {{- if .Values.postgresql.caCert }}
            - --postgres-ca-cert={{ .Values.postgresql.caCert }}
            {{- end }}
            {{- if .Values.postgresql.clientCert }}
            - --postgres-client-cert={{ .Values.postgresql.clientCert }}
            {{- end }}
            {{- if .Values.postgresql.clientKey }}
            - --postgres-client-key={{ .Values.postgresql.clientKey }}
            {{- end }}
            {{- if .Values.postgresql.connectTimeout }}
            - --postgres-connect-timeout={{ .Values.postgresql.connectTimeout }}
            {{- end }}
          {{- if .Values.postgresql.existingSecret }}
          env:
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: {{ .Values.postgresql.passwordSecretKey }}
          {{- end }}
          {{- if or .Values.web.tls.enabled .Values.web.extraVolumeMounts }}
          volumeMounts:
            {{- with .Values.web.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      containers:
        - name: concourse-web
          image: {{ include "concourse.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - web
            # PostgreSQL
            - --postgres-host={{ include "concourse.postgresHost" . }}
            - --postgres-port={{ include "concourse.postgresPort" . }}
            {{- if .Values.postgresql.socket }}
            - --postgres-socket={{ .Values.postgresql.socket }}
            {{- end }}
            - --postgres-user={{ .Values.postgresql.user }}
            {{- if not .Values.postgresql.existingSecret }}
            - --postgres-password={{ .Values.postgresql.password }}
            {{- end }}
            - --postgres-database={{ .Values.postgresql.database }}
            {{- if ne .Values.postgresql.sslmode "disable" }}
            - --postgres-sslmode={{ .Values.postgresql.sslmode }}
            {{- end }}
            {{- if .Values.postgresql.caCert }}
            - --postgres-ca-cert={{ .Values.postgresql.caCert }}
            {{- end }}
            {{- if .Values.postgresql.clientCert }}
            - --postgres-client-cert={{ .Values.postgresql.clientCert }}
            {{- end }}
            {{- if .Values.postgresql.clientKey }}
            - --postgres-client-key={{ .Values.postgresql.clientKey }}
            {{- end }}
            {{- if .Values.postgresql.connectTimeout }}
            - --postgres-connect-timeout={{ .Values.postgresql.connectTimeout }}
            {{- end }}
            # Web
            - --external-url={{ .Values.web.externalUrl }}
            - --cluster-name={{ .Values.web.clusterName }}
            - --log-level={{ .Values.web.logLevel }}
            # Auth
            - --add-local-user={{ .Values.web.localUsers }}
            - --main-team-local-user={{ .Values.web.mainTeamLocalUser }}
            {{- if .Values.web.tls.enabled }}
            # TLS
            - --tls-bind-port={{ .Values.web.tls.bindPort }}
            - --tls-cert={{ .Values.web.tls.mountPath }}/{{ .Values.web.tls.certFilename }}
            - --tls-key={{ .Values.web.tls.mountPath }}/{{ .Values.web.tls.keyFilename }}
            {{- end }}
            # Kubernetes runtime
            - --kubernetes-namespace={{ include "concourse.kubernetesNamespace" . }}
            {{- if .Values.kubernetes.serviceAccount }}
            - --kubernetes-service-account={{ .Values.kubernetes.serviceAccount }}
            {{- end }}
            {{- if .Values.kubernetes.podStartupTimeout }}
            - --kubernetes-pod-startup-timeout={{ .Values.kubernetes.podStartupTimeout }}
            {{- end }}
            {{- if .Values.kubernetes.artifactHelperImage }}
            - --kubernetes-artifact-helper-image={{ .Values.kubernetes.artifactHelperImage }}
            {{- end }}
            {{- if .Values.kubernetes.imageRegistryPrefix }}
            - --kubernetes-image-registry-prefix={{ .Values.kubernetes.imageRegistryPrefix }}
            {{- end }}
            {{- if .Values.kubernetes.imageRegistrySecret }}
            - --kubernetes-image-registry-secret={{ .Values.kubernetes.imageRegistrySecret }}
            {{- end }}
            {{- range .Values.kubernetes.imagePullSecrets }}
            - --kubernetes-image-pull-secret={{ . }}
            {{- end }}
            # PVCs
            {{- if .Values.cachePvc.enabled }}
            - --kubernetes-cache-pvc={{ .Values.cachePvc.name }}
            {{- end }}
            {{- if .Values.artifactStorePvc.enabled }}
            - --kubernetes-artifact-store-claim={{ .Values.artifactStorePvc.name }}
            {{- if .Values.artifactStorePvc.gcsFuse.enabled }}
            - --kubernetes-artifact-store-gcs-fuse
            {{- end }}
            {{- end }}
            # Extra args
            {{- range .Values.web.extraArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: CONCOURSE_SESSION_SIGNING_KEY
              value: /keys/session_signing_key
            - name: CONCOURSE_TSA_HOST_KEY
              value: /keys/tsa_host_key
            - name: CONCOURSE_TSA_AUTHORIZED_KEYS
              value: /keys/authorized_worker_keys
            {{- if .Values.postgresql.existingSecret }}
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.existingSecret }}
                  key: {{ .Values.postgresql.passwordSecretKey }}
            {{- end }}
            {{- range .Values.web.env }}
            - {{- toYaml . | nindent 14 }}
            {{- end }}
          ports:
            - containerPort: 8080
              name: http
            {{- if .Values.web.tls.enabled }}
            - containerPort: {{ .Values.web.tls.bindPort }}
              name: https
            {{- end }}
            - containerPort: 2222
              name: tsa
          {{- with .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: keys
              mountPath: /keys
              readOnly: true
            {{- if .Values.web.tls.enabled }}
            - name: web-tls
              mountPath: {{ .Values.web.tls.mountPath }}
              readOnly: true
            {{- end }}
            {{- with .Values.web.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: keys
          emptyDir: {}
        {{- if .Values.web.tls.enabled }}
        - name: web-tls
          secret:
            secretName: {{ .Values.web.tls.secretName }}
        {{- end }}
        {{- with .Values.web.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
